name: "Setup Solana"
description: "Setup Solana"
runs:
  using: "composite"
  steps:
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.SOLANA_CLI_VERSION }}
      - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
      - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - run: yes | solana-keygen new
