name: Core Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env: 
  SOLANA_CLI_VERSION: 1.8.0
  NODE_VERSION: 17.0.1

jobs:
  test:
    name: Core Tests
    runs-on: ubuntu-18.04
    steps:
      - run: rustup component add rustfmt clippy
      - run: echo "ANCHOR_VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: sudo apt-get install -y pkg-config build-essential libudev-dev
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
      - run: pushd ts && yarn && popd
      - run: pushd ts && yarn test && popd
      - run: pushd ts && yarn lint && popd
